
--
-- Contenu de la table 'Country'
--

INSERT INTO Country VALUES('af', 'Afghanistan');
INSERT INTO Country VALUES('ax', 'Aland Islands');
INSERT INTO Country VALUES('al', 'Albania');
INSERT INTO Country VALUES('dz', 'Algeria');
INSERT INTO Country VALUES('as', 'American Samoa');
INSERT INTO Country VALUES('ad', 'Andorra');
INSERT INTO Country VALUES('ao', 'Angola');
INSERT INTO Country VALUES('ai', 'Anguilla');
INSERT INTO Country VALUES('aq', 'Antarctica');
INSERT INTO Country VALUES('ag', 'Antigua and Barbuda');
INSERT INTO Country VALUES('ar', 'Argentina');
INSERT INTO Country VALUES('am', 'Armenia');
INSERT INTO Country VALUES('aw', 'Aruba');
INSERT INTO Country VALUES('au', 'Australia');
INSERT INTO Country VALUES('at', 'Austria');
INSERT INTO Country VALUES('az', 'Azerbaijan');
INSERT INTO Country VALUES('bs', 'Bahamas');
INSERT INTO Country VALUES('bh', 'Bahrain');
INSERT INTO Country VALUES('bd', 'Bangladesh');
INSERT INTO Country VALUES('bb', 'Barbados');
INSERT INTO Country VALUES('by', 'Belarus');
INSERT INTO Country VALUES('be', 'Belgium');
INSERT INTO Country VALUES('bz', 'Belize');
INSERT INTO Country VALUES('bj', 'Benin');
INSERT INTO Country VALUES('bm', 'Bermuda');
INSERT INTO Country VALUES('bt', 'Bhutan');
INSERT INTO Country VALUES('bo', 'Bolivia');
INSERT INTO Country VALUES('ba', 'Bosnia and Herzegovina');
INSERT INTO Country VALUES('bw', 'Botswana');
INSERT INTO Country VALUES('bv', 'Bouvet Island');
INSERT INTO Country VALUES('br', 'Brazil');
INSERT INTO Country VALUES('io', 'British Indian Ocean Territory');
INSERT INTO Country VALUES('bn', 'Brunei Darussalam');
INSERT INTO Country VALUES('bg', 'Bulgaria');
INSERT INTO Country VALUES('bf', 'Burkina Faso');
INSERT INTO Country VALUES('bi', 'Burundi');
INSERT INTO Country VALUES('kh', 'Cambodia');
INSERT INTO Country VALUES('cm', 'Cameroon');
INSERT INTO Country VALUES('ca', 'Canada');
INSERT INTO Country VALUES('cv', 'Cape Verde');
INSERT INTO Country VALUES('ky', 'Cayman Islands');
INSERT INTO Country VALUES('cf', 'Central African Republic');
INSERT INTO Country VALUES('td', 'Chad');
INSERT INTO Country VALUES('cl', 'Chile');
INSERT INTO Country VALUES('cn', 'China');
INSERT INTO Country VALUES('cx', 'Christmas Island');
INSERT INTO Country VALUES('cc', 'Cocos (Keeling) Islands');
INSERT INTO Country VALUES('co', 'Colombia');
INSERT INTO Country VALUES('km', 'Comoros');
INSERT INTO Country VALUES('cg', 'Congo');
INSERT INTO Country VALUES('cd', 'Congo, The Democratic Republic of the');
INSERT INTO Country VALUES('ck', 'Cook Islands');
INSERT INTO Country VALUES('cr', 'Costa Rica');
INSERT INTO Country VALUES('ci', 'Cote D''Ivoire');
INSERT INTO Country VALUES('hr', 'Croatia');
INSERT INTO Country VALUES('cu', 'Cuba');
INSERT INTO Country VALUES('cy', 'Cyprus');
INSERT INTO Country VALUES('cz', 'Czech Republic');
INSERT INTO Country VALUES('dk', 'Denmark');
INSERT INTO Country VALUES('dj', 'Djibouti');
INSERT INTO Country VALUES('dm', 'Dominica');
INSERT INTO Country VALUES('do', 'Dominican Republic');
INSERT INTO Country VALUES('ec', 'Ecuador');
INSERT INTO Country VALUES('eg', 'Egypt');
INSERT INTO Country VALUES('sv', 'El Salvador');
INSERT INTO Country VALUES('gq', 'Equatorial Guinea');
INSERT INTO Country VALUES('er', 'Eritrea');
INSERT INTO Country VALUES('ee', 'Estonia');
INSERT INTO Country VALUES('et', 'Ethiopia');
INSERT INTO Country VALUES('fk', 'Falkland Islands (Malvinas)');
INSERT INTO Country VALUES('fo', 'Faroe Islands');
INSERT INTO Country VALUES('fj', 'Fiji');
INSERT INTO Country VALUES('fi', 'Finland');
INSERT INTO Country VALUES('fr', 'France');
INSERT INTO Country VALUES('fx', 'France, Metropolitan');
INSERT INTO Country VALUES('gf', 'French Guiana');
INSERT INTO Country VALUES('pf', 'French Polynesia');
INSERT INTO Country VALUES('tf', 'French Southern Territories');
INSERT INTO Country VALUES('ga', 'Gabon');
INSERT INTO Country VALUES('gm', 'Gambia');
INSERT INTO Country VALUES('ge', 'Georgia');
INSERT INTO Country VALUES('de', 'Germany');
INSERT INTO Country VALUES('gh', 'Ghana');
INSERT INTO Country VALUES('gi', 'Gibraltar');
INSERT INTO Country VALUES('gr', 'Greece');
INSERT INTO Country VALUES('gl', 'Greenland');
INSERT INTO Country VALUES('gd', 'Grenada');
INSERT INTO Country VALUES('gp', 'Guadeloupe');
INSERT INTO Country VALUES('gu', 'Guam');
INSERT INTO Country VALUES('gt', 'Guatemala');
INSERT INTO Country VALUES('gn', 'Guinea');
INSERT INTO Country VALUES('gw', 'Guinea-Bissau');
INSERT INTO Country VALUES('gy', 'Guyana');
INSERT INTO Country VALUES('ht', 'Haiti');
INSERT INTO Country VALUES('hm', 'Heard Island and McDonald Islands');
INSERT INTO Country VALUES('va', 'Holy See (Vatican City State)');
INSERT INTO Country VALUES('hn', 'Honduras');
INSERT INTO Country VALUES('hk', 'Hong Kong');
INSERT INTO Country VALUES('hu', 'Hungary');
INSERT INTO Country VALUES('is', 'Iceland');
INSERT INTO Country VALUES('in', 'India');
INSERT INTO Country VALUES('id', 'Indonesia');
INSERT INTO Country VALUES('ir', 'Iran, Islamic Republic of');
INSERT INTO Country VALUES('iq', 'Iraq');
INSERT INTO Country VALUES('ie', 'Ireland');
INSERT INTO Country VALUES('il', 'Israel');
INSERT INTO Country VALUES('it', 'Italy');
INSERT INTO Country VALUES('jm', 'Jamaica');
INSERT INTO Country VALUES('jp', 'Japan');
INSERT INTO Country VALUES('jo', 'Jordan');
INSERT INTO Country VALUES('kz', 'Kazakhstan');
INSERT INTO Country VALUES('ke', 'Kenya');
INSERT INTO Country VALUES('ki', 'Kiribati');
INSERT INTO Country VALUES('kp', 'Korea, Democratic People''s Republic of');
INSERT INTO Country VALUES('kr', 'Korea, Republic of');
INSERT INTO Country VALUES('kw', 'Kuwait');
INSERT INTO Country VALUES('kg', 'Kyrgyzstan');
INSERT INTO Country VALUES('la', 'Lao People''s Democratic Republic');
INSERT INTO Country VALUES('lv', 'Latvia');
INSERT INTO Country VALUES('lb', 'Lebanon');
INSERT INTO Country VALUES('ls', 'Lesotho');
INSERT INTO Country VALUES('lr', 'Liberia');
INSERT INTO Country VALUES('ly', 'Libyan Arab Jamahiriya');
INSERT INTO Country VALUES('li', 'Liechtenstein');
INSERT INTO Country VALUES('lt', 'Lithuania');
INSERT INTO Country VALUES('lu', 'Luxembourg');
INSERT INTO Country VALUES('mo', 'Macao');
INSERT INTO Country VALUES('mk', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO Country VALUES('mg', 'Madagascar');
INSERT INTO Country VALUES('mw', 'Malawi');
INSERT INTO Country VALUES('my', 'Malaysia');
INSERT INTO Country VALUES('mv', 'Maldives');
INSERT INTO Country VALUES('ml', 'Mali');
INSERT INTO Country VALUES('mt', 'Malta');
INSERT INTO Country VALUES('mh', 'Marshall Islands');
INSERT INTO Country VALUES('mq', 'Martinique');
INSERT INTO Country VALUES('mr', 'Mauritania');
INSERT INTO Country VALUES('mu', 'Mauritius');
INSERT INTO Country VALUES('yt', 'Mayotte');
INSERT INTO Country VALUES('mx', 'Mexico');
INSERT INTO Country VALUES('fm', 'Micronesia, Federated States of');
INSERT INTO Country VALUES('md', 'Moldova, Republic of');
INSERT INTO Country VALUES('mc', 'Monaco');
INSERT INTO Country VALUES('mn', 'Mongolia');
INSERT INTO Country VALUES('ms', 'Montserrat');
INSERT INTO Country VALUES('ma', 'Morocco');
INSERT INTO Country VALUES('mz', 'Mozambique');
INSERT INTO Country VALUES('mm', 'Myanmar');
INSERT INTO Country VALUES('na', 'Namibia');
INSERT INTO Country VALUES('nr', 'Nauru');
INSERT INTO Country VALUES('np', 'Nepal');
INSERT INTO Country VALUES('nl', 'Netherlands');
INSERT INTO Country VALUES('an', 'Netherlands Antilles');
INSERT INTO Country VALUES('nc', 'New Caledonia');
INSERT INTO Country VALUES('nz', 'New Zealand');
INSERT INTO Country VALUES('ni', 'Nicaragua');
INSERT INTO Country VALUES('ne', 'Niger');
INSERT INTO Country VALUES('ng', 'Nigeria');
INSERT INTO Country VALUES('nu', 'Niue');
INSERT INTO Country VALUES('nf', 'Norfolk Island');
INSERT INTO Country VALUES('mp', 'Northern Mariana Islands');
INSERT INTO Country VALUES('no', 'Norway');
INSERT INTO Country VALUES('om', 'Oman');
INSERT INTO Country VALUES('pk', 'Pakistan');
INSERT INTO Country VALUES('pw', 'Palau');
INSERT INTO Country VALUES('ps', 'Palestinian Territory, Occupied');
INSERT INTO Country VALUES('pa', 'Panama');
INSERT INTO Country VALUES('pg', 'Papua New Guinea');
INSERT INTO Country VALUES('py', 'Paraguay');
INSERT INTO Country VALUES('pe', 'Peru');
INSERT INTO Country VALUES('ph', 'Philippines');
INSERT INTO Country VALUES('pn', 'Pitcairn');
INSERT INTO Country VALUES('pl', 'Poland');
INSERT INTO Country VALUES('pt', 'Portugal');
INSERT INTO Country VALUES('pr', 'Puerto Rico');
INSERT INTO Country VALUES('qa', 'Qatar');
INSERT INTO Country VALUES('re', 'Reunion');
INSERT INTO Country VALUES('ro', 'Romania');
INSERT INTO Country VALUES('ru', 'Russian Federation');
INSERT INTO Country VALUES('rw', 'Rwanda');
INSERT INTO Country VALUES('sh', 'Saint Helena');
INSERT INTO Country VALUES('kn', 'Saint Kitts and Nevis');
INSERT INTO Country VALUES('lc', 'Saint Lucia');
INSERT INTO Country VALUES('pm', 'Saint Pierre and Miquelon');
INSERT INTO Country VALUES('vc', 'Saint Vincent and the Grenadines');
INSERT INTO Country VALUES('ws', 'Samoa');
INSERT INTO Country VALUES('sm', 'San Marino');
INSERT INTO Country VALUES('st', 'Sao Tome and Principe');
INSERT INTO Country VALUES('sa', 'Saudi Arabia');
INSERT INTO Country VALUES('sn', 'Senegal');
INSERT INTO Country VALUES('cs', 'Serbia and Montenegro');
INSERT INTO Country VALUES('sc', 'Seychelles');
INSERT INTO Country VALUES('sl', 'Sierra Leone');
INSERT INTO Country VALUES('sg', 'Singapore');
INSERT INTO Country VALUES('sk', 'Slovakia');
INSERT INTO Country VALUES('si', 'Slovenia');
INSERT INTO Country VALUES('sb', 'Solomon Islands');
INSERT INTO Country VALUES('so', 'Somalia');
INSERT INTO Country VALUES('za', 'South Africa');
INSERT INTO Country VALUES('gs', 'South Georgia and the South Sandwich Islands');
INSERT INTO Country VALUES('es', 'Spain');
INSERT INTO Country VALUES('lk', 'Sri Lanka');
INSERT INTO Country VALUES('sd', 'Sudan');
INSERT INTO Country VALUES('sr', 'Suriname');
INSERT INTO Country VALUES('sj', 'Svalbard and Jan Mayen');
INSERT INTO Country VALUES('sz', 'Swaziland');
INSERT INTO Country VALUES('se', 'Sweden');
INSERT INTO Country VALUES('ch', 'Switzerland');
INSERT INTO Country VALUES('sy', 'Syrian Arab Republic');
INSERT INTO Country VALUES('tw', 'Taiwan');
INSERT INTO Country VALUES('tj', 'Tajikistan');
INSERT INTO Country VALUES('tz', 'Tanzania, United Republic of');
INSERT INTO Country VALUES('th', 'Thailand');
INSERT INTO Country VALUES('tl', 'Timor-Leste');
INSERT INTO Country VALUES('tg', 'Togo');
INSERT INTO Country VALUES('tk', 'Tokelau');
INSERT INTO Country VALUES('to', 'Tonga');
INSERT INTO Country VALUES('tt', 'Trinidad and Tobago');
INSERT INTO Country VALUES('tn', 'Tunisia');
INSERT INTO Country VALUES('tr', 'Turkey');
INSERT INTO Country VALUES('tm', 'Turkmenistan');
INSERT INTO Country VALUES('tc', 'Turks and Caicos Islands');
INSERT INTO Country VALUES('tv', 'Tuvalu');
INSERT INTO Country VALUES('ug', 'Uganda');
INSERT INTO Country VALUES('ua', 'Ukraine');
INSERT INTO Country VALUES('ae', 'United Arab Emirates');
INSERT INTO Country VALUES('gb', 'United Kingdom');
INSERT INTO Country VALUES('us', 'United States');
INSERT INTO Country VALUES('um', 'United States Minor Outlying Islands');
INSERT INTO Country VALUES('uy', 'Uruguay');
INSERT INTO Country VALUES('uz', 'Uzbekistan');
INSERT INTO Country VALUES('vu', 'Vanuatu');
INSERT INTO Country VALUES('ve', 'Venezuela');
INSERT INTO Country VALUES('vn', 'Vietnam');
INSERT INTO Country VALUES('vg', 'Virgin Islands, British');
INSERT INTO Country VALUES('vi', 'Virgin Islands, U.S.');
INSERT INTO Country VALUES('wf', 'Wallis and Futuna');
INSERT INTO Country VALUES('eh', 'Western Sahara');
INSERT INTO Country VALUES('ye', 'Yemen');
INSERT INTO Country VALUES('zm', 'Zambia');
INSERT INTO Country VALUES('zw', 'Zimbabwe');
